LIB "tst.lib";
tst_init();
ring r=0,(x,y,z),dp;
ncalgebra(-1,0); 
ideal m = maxideal(1);
m;
poly f = x2;
poly g = y3;
ideal i = x*y*z , f-g, g*(x-y) + f^4 ,0, 2x-z2y;
ideal M = i + maxideal(10);
timer =0;
i = M*M;
tst_ignore(timer, "time");
ncols(i);
timer =0;
i = M^2;
ncols(i);
tst_ignore(timer, "time");
i[ncols(i)];
vector v = [x,y-z,x2,y-x,x2yz2-y];
ideal j = ideal(v);
j;
tst_status(1);$
