# -*- mode: cmake; -*-
#
#
#

function(libfac_mk_version GEN_H_FILE)
  set(_GEN_H_FILE ${CMAKE_CURRENT_BINARY_DIR}/version.h)
  set(_version "${LIBFAC_V_MAJOR}.${LIBFAC_V_MINOR}.${LIBFAC_V_PATCH}")

  file(WRITE  ${_GEN_H_FILE} "/* generated by cmake */\n")
  file(APPEND ${_GEN_H_FILE} "/**\n")
  file(APPEND ${_GEN_H_FILE} "   ${LIBFAC_NAME}\n")
  file(APPEND ${_GEN_H_FILE} "  @author ${LIBFAC_AUTHOR}\n")
  file(APPEND ${_GEN_H_FILE} "*/\n")


  file(APPEND ${_GEN_H_FILE} "#define LIBFAC_VERSION \"${_version}\"\n")
  file(APPEND ${_GEN_H_FILE} "#define LIBFAC_DATE    \"${LIBFAC_DATE}\"\n")

  set(${GEN_H_FILE} ${${GEN_H_FILE}} PARENT_SCOPE)
endfunction()
