#!/bin/sh
if [ -f mod_grammar.hh ]
then
  mv mod_grammar.hh mod_grammar.cc.h
fi
if [ -f mod_grammar.h ]
then
  if diff mod_grammar.cc.h mod_grammar.h >/dev/null
  then
    echo mod_grammar.h was okay
    /bin/rm mod_grammar.cc.h
  else
    echo generating new mod_grammar.h
    mv mod_grammar.cc.h mod_grammar.h
  fi
else
  echo generating mod_grammar.h
  mv mod_grammar.cc.h mod_grammar.h
fi
