/*
 * This was automaticly generated by modgen
 * version 0.2
 * module pcv
 * Don't edit this file
 */


#line 113 "pcv.cc"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>


#include <locals.h>

BOOLEAN mod_MinDeg(leftv res, leftv h);
//int pcvMinDeg(poly p);

BOOLEAN mod_P2CV(leftv res, leftv h);
//lists pcvP2CV(lists pl, int d0, int d1);

BOOLEAN mod_CV2P(leftv res, leftv h);
//lists pcvCV2P(lists pl, int d0, int d1);

BOOLEAN mod_Dim(leftv res, leftv h);
//int pcvDim(int d0, int d1);

BOOLEAN mod_Basis(leftv res, leftv h);
//lists pcvBasis(int d0, int d1);

