LIB "tst.lib"; tst_init();
LIB "ncdecomp.lib";
printlevel=0;
option(returnSB);
def a = makeUsl2(); // U(sl_2) in characteristic 0
setring a;
ideal I = e3,f3,h3-4*h;
I = twostd(I);           // two-sided ideal generated by I
vdim(I);                 // it is finite-dimensional
ideal Cn = 4*e*f+h^2-2*h; // the only central element
list T = CenCharDec(I,Cn);
T;
// consider another example
ideal J = e*f*h;
CenCharDec(J,Cn);
tst_status(1);$
