LIB "tst.lib"; tst_init();
LIB "multigrading.lib";
// ----------- extreme case ------------ //
intmat S[1][3] =
1,  -1, 10;
// Torsion:
intmat L[1][1] =
0;
// The free subgroup generated by elements of S within Z^1
// can be constructed as follows:
// shortcut:
def G = createTorsionFreeGroup(S);
printGroup(G);
// the general way:
def GG = createGroup(S, L); // (S+L)/L
printGroup(GG);
tst_status(1);$
