#!/bin/sh
echo "width=400;" >$1.pic
echo "height=400;" >>$1.pic
cat $1 >>$1.pic
echo "color_file_format = jpg;">>$1.pic
echo "filename = \"/tmp/surf\";">>$1.pic
echo "save_color_image;">>$1.pic
surf $1.pic
/bin/rm $1*
cygstart /tmp/surf.jpg
