# $Id: Makefile,v 1.2 2003-11-03 17:31:19 Singular Exp $
#################################################
SHELL		= /bin/sh

##
## Primary targets
##

all: 
	cd src;$(MAKE);cd ..

install:	all
	cd src;$(MAKE) install;cd ..

clean:
	cd src;$(MAKE) clean;cd ..
