# $Id: Makefile,v 1.3 2004-01-29 13:36:54 Singular Exp $
#################################################
SHELL		= /bin/sh

##
## Primary targets
##

all: 
	cd src;$(MAKE) ntl.a;cd ..

install:	all
	cd src;$(MAKE) install;cd ..

clean:
	cd src;$(MAKE) clean;cd ..
