/****************************************
*  Computer Algebra System SINGULAR     *
****************************************/
/*
* ABSTRACT: border bases in rational Weyl algebras
*/

#include "kernel/mod2.h"

#include "kernel/GBEngine/ratborderbasis.h"

#ifdef HAVE_RATGRING

#include <climits>

#include "kernel/GBEngine/borderbasis_staircase.h"
#include "kernel/GBEngine/ratgring.h"
#include "kernel/ideals.h"
#include "kernel/polys.h"
#include "polys/monomials/p_polys.h"
#include "polys/monomials/ring.h"
#include "polys/nc/nc.h"
#include "reporter/reporter.h"

namespace
{
static poly copyRationalHead(const poly p, const int coefficientVariables,
                             const ring r)
{
  poly copy = p_Copy(p, r);
  poly head = p_HeadRat(copy, coefficientVariables, r);
  if (head != copy) p_Delete(&copy, r);
  return head;
}

// Pseudo-reduce the leading differential monomial of dividend by reducer.
// Besides the reduced polynomial, return the coefficient polynomial by which
// dividend was multiplied.  This is the bookkeeping omitted by redRat and is
// needed to recover a fraction-free border relation.
static poly rationalHeadReduction(const poly reducer, poly dividend,
                                  const int coefficientVariables,
                                  poly &scale, const ring r)
{
  poly multiplier = p_One(r);
  p_ExpVectorDiffRat(multiplier, dividend, reducer, coefficientVariables, r);

  poly reducerHead = copyRationalHead(reducer, coefficientVariables, r);
  poly multipliedHead = nc_mm_Mult_p(multiplier, reducerHead, r);
  poly reducerCoefficient =
      p_GetCoeffRat(multipliedHead, coefficientVariables, r);
  poly dividendCoefficient =
      p_GetCoeffRat(dividend, coefficientVariables, r);

  poly reducerTail = p_Copy(reducer, r);
  p_LmDeleteAndNextRat(&reducerTail, coefficientVariables, r);

  ideal coefficientSyzygy =
      ncGCD(dividendCoefficient, reducerCoefficient, r);
  poly dividendScale = coefficientSyzygy->m[0];
  coefficientSyzygy->m[0] = NULL;
  poly reducerScale = coefficientSyzygy->m[1];
  coefficientSyzygy->m[1] = NULL;
  id_Delete(&coefficientSyzygy, r);

  scale = p_Copy(dividendScale, r);

  p_LmDeleteAndNextRat(&dividend, coefficientVariables, r);
  p_LmDeleteAndNextRat(&multipliedHead, coefficientVariables, r);

  dividend = p_Mult_q(dividendScale, dividend, r);
  reducerTail = nc_mm_Mult_p(multiplier, reducerTail, r);
  p_Delete(&multiplier, r);
  reducerTail = p_Add_q(multipliedHead, reducerTail, r);
  reducerTail = p_Mult_q(reducerScale, reducerTail, r);
  return p_Add_q(dividend, reducerTail, r);
}

static int rationalReducer(const ideal G, const poly p,
                           const int coefficientVariables, const ring r)
{
  int best = -1;
  int bestLength = INT_MAX;
  for (int i = 0; i < IDELEMS(G); ++i)
  {
    if ((G->m[i] != NULL) &&
        p_DivisibleByRat(G->m[i], p, coefficientVariables, r))
    {
      const int length = pLength(G->m[i]);
      if (length < bestLength)
      {
        best = i;
        bestLength = length;
      }
    }
  }
  return best;
}

// Return remainder and denominator such that
// denominator * input - remainder belongs to the localized ideal generated by
// G.  Irreducible differential head terms are saved while reducible lower
// terms continue to be processed, yielding a full rather than a top normal
// form.
static poly rationalNormalForm(poly input, const ideal G,
                               const int coefficientVariables,
                               poly &denominator, const ring r)
{
  poly work = input;
  poly remainder = NULL;
  denominator = p_One(r);

  while (work != NULL)
  {
    const int reducer = rationalReducer(G, work, coefficientVariables, r);
    if (reducer < 0)
    {
      poly head = copyRationalHead(work, coefficientVariables, r);
      p_LmDeleteAndNextRat(&work, coefficientVariables, r);
      remainder = p_Add_q(remainder, head, r);
      continue;
    }

    poly scale = NULL;
    work = rationalHeadReduction(G->m[reducer], work,
                                 coefficientVariables, scale, r);
    if (remainder != NULL)
      remainder = p_Mult_q(p_Copy(scale, r), remainder, r);
    denominator = p_Mult_q(scale, denominator, r);
  }
  return remainder;
}
}

BOOLEAN nc_RationalWeylBorderBasis(const ideal G, int coefficientVariables,
                                   ideal &orderIdeal, ideal &borderBasis,
                                   const ring r)
{
  orderIdeal = NULL;
  borderBasis = NULL;
  if (!rIsPluralRing(r))
  {
    WerrorS("rational Weyl border basis: expected a noncommutative G-algebra");
    return TRUE;
  }
  if ((coefficientVariables <= 0) || (coefficientVariables >= r->N))
  {
    WerrorS("rational Weyl border basis: invalid coefficient-variable block");
    return TRUE;
  }
  if (!rHasGlobalOrdering(r))
  {
    WerrorS("rational Weyl border basis: expected a global antiblock ordering");
    return TRUE;
  }

  const int firstOperator = coefficientVariables + 1;
  const int operators = r->N - coefficientVariables;
  borderbasis_kernel::ExponentVectors standard;
  borderbasis_kernel::ExponentVectors border;
  if (borderbasis_kernel::staircase(G, firstOperator, operators, standard,
                                    border, r))
    return TRUE;

  orderIdeal =
      borderbasis_kernel::makeMonomialIdeal(standard, firstOperator, r);
  borderBasis = idInit(static_cast<int>(border.size()), 1);
  for (size_t i = 0; i < border.size(); ++i)
  {
    poly b = borderbasis_kernel::makeMonomial(border[i], firstOperator, r);
    poly denominator = NULL;
    poly normalForm = rationalNormalForm(p_Copy(b, r), G,
                                         coefficientVariables, denominator, r);
    poly leadingPart = p_Mult_q(denominator, b, r);
    borderBasis->m[i] = p_Sub(leadingPart, normalForm, r);
  }
  return FALSE;
}

#endif
