
#include <Python.h>
#include <boost/python.hpp>
env = Environment()
conf = Configure(env)
if not conf.CheckCHeader('/usr/include/python2.3/Python.h'):
    print 'Python 2.3 must be installed'
    Exit(1)

conf.env.Append(CPPPATH=["/usr/include/python2.3"])
if not conf.CheckCXXHeader('boost/python.hpp'):
    print 'Boost/python must be installed'
    Exit(1)

if not conf.CheckCXXHeader('boost/shared_ptr.hpp'):
    print 'Boost must be installed'
    Exit(1)
    
conf.env.Append(CPPPATH=["../../kernel"])
if not conf.CheckCHeader('mod2.h'):
    print 'must have a Singular build directory'
    Exit(1)
env = conf.Finish()

SING_ROOT="../.."
SING_ARCH="ix86-Linux"
PYTHON_VERSION="2.3"
SharedLibrary("python_module", 
              ["python.cc", "poly_wrap.cc", "vector_wrap.cc", "CF_wrap.cc",\
             "number_wrap.cc", "playground.cc"],
           
              CPPPATH=[".", SING_ROOT+"/kernel",\
                       SING_ROOT+"/Singular", SING_ROOT+"/"+SING_ARCH +"/include",\
                       "/usr/include/python"+PYTHON_VERSION],
              LIBS=["boost_python","python"+PYTHON_VERSION], CPPDEFINES=["NDEBUG","DBUILD_MODULE"], SHLIBPREFIX="")


