LIB "polylib.lib";
example cyclic;
example freerank;
example is_zero;
example maxcoef;
example maxdeg;
example maxdeg1;
example mindeg;
example mindeg1;
example normalize;
LIB "tst.lib";tst_status(1);$
