LIB "ring.lib";
example changechar;
example changeord;
example changevar;
example defring;
example defrings;
example defringp;
example extendring;
example fetchall;
example imapall;
example mapall;
example ringtensor;
example ringweights;
LIB "tst.lib";tst_status(1);$
