#! /bin/sh


#############################################################################################################
# !!!!!!!!!!!!!!!!! Please put a copy of the installed '$PREFIX/bin/libpolys-config' here !!!!!!!!!!!!!!!!!!!
#############################################################################################################



# NAME="tt"
NAME="test"

P="."
# /mnt/DATA/GITHUB/w/GAP/libsing/spielwiese/TARGET/bin"

LIBPOLYSCFLAGS="`sh $P/libsingular-config --cflagsg` -g -Wextra -Winline -Wall -Wno-long-long  -O0 -fno-exceptions"
LIBPOLYSLIBS=`sh $P/libsingular-config --libsg`
LIBPOLYSPREFIX="`sh $P/libsingular-config --prefix`"

echo "Using libpolys from: '$LIBPOLYSPREFIX'"
echo "Using        CFLAGS: '$LIBPOLYSCFLAGS'"
echo "Using          LIBS: '$LIBPOLYSLIBS'"

CMD="g++ $LIBPOLYSCFLAGS -c $NAME.cc "
echo "executing '$CMD':"
$CMD
# -rdynamic
CMD="g++ -static -g -Wextra -Winline -Wall -Wno-long-long -O0 -fno-exceptions $NAME.o -o $NAME $LIBPOLYSLIBS"
echo "executing '$CMD':"
$CMD

SINGULARPATH="$LIBPOLYSPREFIX/share/gftables:$LIBPOLYSPREFIX/bin" SINGULAR_ROOT_DIR="$LIBPOLYSPREFIX" ./$NAME
