name: CI with Singular.jl

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
      - 'spielwiese'

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the default repository branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref_name != github.event.repository.default_branch || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - Singular.jl ${{ matrix.singularjl-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        singularjl-version:
          - 'latest-release'
          - 'master'
        julia-version:
          - '1.10'
          - '1'         # latest stable release
          - 'nightly'
        os:
          - ubuntu-latest
        include:
          # Add a few macOS jobs (the number we can run in parallel is limited)
          - singularjl-version: 'latest-release'
            julia-version: '1'
            os: macOS-latest
          - singularjl-version: 'master'
            julia-version: '1'
            os: macOS-latest

    steps:
      - name: Checkout Singular
        uses: actions/checkout@v6
        with:
          path: 'SINGULARROOT'
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - name: Install Singular.jl
        shell: julia --color=yes {0}
        run: |
          using Pkg
          if "${{ matrix.singularjl-version }}" == "latest-release"
            Pkg.add("Singular")
          else
            Pkg.add(; name="Singular", rev="${{ matrix.singularjl-version }}")
          end
          path = dirname(dirname(Base.find_package("Singular")))
          open(ENV["GITHUB_ENV"], "a") do io
              println(io, "SINGULARJL_PATH=$path")
          end
      - name: "Install dependencies (for macOS)"
        if: runner.os == 'macOS'
        run: |
          brew install autoconf automake libtool
      - name: "Run autogen.sh in SINGULARROOT"
        run: |
          mv SINGULARROOT /tmp/SINGULARROOT
          cd /tmp/SINGULARROOT
          ./autogen.sh
      - name: "Override bundled Singular"
        run: |
          julia --proj=override $SINGULARJL_PATH/etc/setup_override_dir.jl /tmp/SINGULARROOT /tmp/singular_jll_override
      - name: "Run tests"
        run: |
          julia --proj=override $SINGULARJL_PATH/etc/run_with_override.jl /tmp/singular_jll_override --depwarn=error -e "using Pkg; Pkg.test(\"Singular\")"
